version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - aws cloudformation package --template-file cfn.yaml --s3-bucket artifacts-nextjs \
                --s3-prefix $S3_BUILDS_PREFIX --output-template-file $TEMPLATE_FILE_NAME
artifacts:
  files:
    - '$TEMPLATE_FILE_NAME'
    - '*config.json'
  discard-paths: yes
