version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  discard-paths: yes
post_build:
  commands: 
    - aws cloudformation package --template-file cfn.yaml --s3-bucket artifacts-nextjs --output-template-file template.yaml
