version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - echo "Changing into source directory $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      - echo "Installing dependencies into src file"
      - npm run build
      - mv * ./src/
      - ls -la
      - aws cloudformation package --template-file cfn.yaml --s3-bucket $S3_BUCKET --output-template-file $TEMPLATE_FILE_NAME
artifacts:
  files:
    - '$TEMPLATE_FILE_NAME'
    - '*config.json'
  discard-paths: yes
